### ISSUE TITLE
missing word, em-dash

### ISSUE THREAD

**Issue by PLP-Consulting** [standardebooks/f-scott-fitzgerald_the-beautiful-and-damned#1]
https://github.com/standardebooks/f-scott-fitzgerald_the-beautiful-and-damned/blob/05cade3768f0e8a594bb710241c0531202241832/src/epub/text/chapter-2-3.xhtml#L929

"<abbr>Mr.</abbr> Brett was not he was expected back in an hour."

should be

"<abbr>Mr.</abbr> Brett was not in—he was expected back in an hour."

**Comment by acabal** [comment]
Thanks, this should be fixed now!
